<?php include '../includes/header-form.php'; ?>

    <div class="container mx-auto px-4 sm:px-6 pt-4 sm:pt-6 pb-8 sm:pb-12">
        <div class="max-w-3xl mx-auto">
            <div class="text-center mb-8 sm:mb-12">
                <h1 class="custom-h1 text-gray-900">Most Accurate AI<br>Brand Strategy For Businesses</h1>
                <p class="custom-p mt-3 sm:mt-4 leading-relaxed text-sm sm:text-base">Answer a few simple questions, and we'll send you a complete brand strategy generated by AI and refined by our expert brand strategists – straight to your inbox.</p>
            </div>

            <div class="bg-white p-4 sm:p-8 md:p-12 rounded-2xl shadow-sm border border-gray-200 hover:border-gray-300 transition-all duration-300">
            <form id="brand-form">
                <input type="hidden" name="contact_number">
                    <div class="space-y-6 sm:space-y-8">
                        <div>
                            <label class="custom-label text-gray-900 font-semibold text-sm sm:text-base">What is your business name, industry and location?</label>
                            <div class="mt-3 sm:mt-4 space-y-3 sm:space-y-4">
                                <input type="text" name="business_name" id="business_name" placeholder="Business name" required class="w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base">
                                <input type="text" name="industry" id="industry" placeholder="Industry" required class="w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base">
                                <input type="text" name="location" id="location" placeholder="Location" required class="w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base">
                            </div>
                        </div>

                        <div>
                            <label for="product-service" class="custom-label text-gray-900 font-semibold text-sm sm:text-base">What is your main product or service?</label>
                            <textarea id="product-service" name="product_service" rows="4" placeholder="We are e-commerce startup selling kitchen items." required class="mt-3 sm:mt-4 w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base"></textarea>
                        </div>

                        <div>
                            <label for="audience" class="custom-label text-gray-900 font-semibold text-sm sm:text-base">Who are your ideal customers (target audience)?</label>
                            <textarea id="audience" name="audience" rows="3" placeholder="Young housewife with a new born baby." required class="mt-3 sm:mt-4 w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base"></textarea>
                        </div>

                        <div>
                            <label for="competitors" class="custom-label text-gray-900 font-semibold text-sm sm:text-base">Who are your top competitors?</label>
                            <textarea id="competitors" name="competitors" rows="3" placeholder="Insert websites of the competitors." required class="mt-3 sm:mt-4 w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base"></textarea>
                        </div>

                        <div>
                            <label for="strengths" class="custom-label text-gray-900 font-semibold text-sm sm:text-base">What makes your brand different (your key strengths)?</label>
                            <textarea id="strengths" name="strengths" rows="3" placeholder="We create special kitchen equipment for our audience." required class="mt-3 sm:mt-4 w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base"></textarea>
                        </div>

                        <div>
                            <label for="brand-feel" class="custom-label text-gray-900 font-semibold text-sm sm:text-base">How should people feel about your brand?</label>
                            <textarea id="brand-feel" name="brand_feel" rows="4" placeholder="I want to feel people my brand is the most durable and high-quality kitchen equipment seller in the country." required class="mt-3 sm:mt-4 w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base"></textarea>
                        </div>

                        <div>
                            <label for="contact-info" class="custom-label text-gray-900 font-semibold text-sm sm:text-base">Enter your email address or WhatsApp number to get the result.</label>
                        </div>
                        
                        <div>
                            <input type="text" id="email" name="contact_info" placeholder="Email or WhatsApp number" required class="w-full px-3 sm:px-4 py-2.5 sm:py-3 bg-white rounded-lg border border-gray-200 focus:border-gray-400 focus:bg-white focus:ring-0 hover:border-gray-300 transition-colors text-gray-800 placeholder-gray-400 text-sm sm:text-base">
                        </div>
                    </div>

                    <div class="mt-8 sm:mt-10 text-center">
                        <button type="submit" class="custom-btn inline-flex items-center justify-center bg-black text-white px-6 sm:px-8 py-2.5 sm:py-3 rounded-full hover:bg-gray-800 transition-all transform hover:scale-105 duration-300 text-sm sm:text-base">
                            Submit
                            <svg class="w-4 sm:w-5 h-4 sm:h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"></path></svg>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

<?php include '../includes/footer-form.php'; ?>
